# Generated by Django 2.2.5 on 2019-09-20 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('FN', 'fundacja'), ('ZL', 'zbiórka lokalna'), ('OP', 'organizacja pozarządowa')], default='FN', max_length=2)),
                ('categories', models.ManyToManyField(to='szlachetna_paczka.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Fundation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('zip_code', models.CharField(max_length=6)),
                ('categories', models.ManyToManyField(to='szlachetna_paczka.Category')),
                ('institution', models.ManyToManyField(to='szlachetna_paczka.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
